### ISSUE TITLE
About Ali-CCP Dataset

### ISSUE THREAD

**Issue by striderdu** [Xiaopengli1/Scenario-Wise-Rec#2]
Hi, xiaopeng @Xiaopengli1 

Thanks for your awesome work!

When I use the Ali-CCP dataset that you processed, I observed some samples where the item ID is 0, but the other properties of these items differ. I would like to know your processing strategy for these samples and whether they have any particular physical meaning.

![aliccp](https://github.com/user-attachments/assets/b60a5084-417f-433e-9408-1597af29061c)

**Comment by Xiaopengli1** [comment]
Thank you for your attention to our work @striderdu ! For the Ali-CCP process, I refer to the data processing from [torch-rechub](https://github.com/datawhalechina/torch-rechub). You can find the process script [here](https://github.com/datawhalechina/torch-rechub/blob/main/examples/ranking/data/ali-ccp/preprocess_ali_ccp.py). I hope this will be helpful to you.

**Comment by striderdu** [comment]
> Thank you for your attention to our work @striderdu ! For the Ali-CCP process, I refer to the data processing from [torch-rechub](https://github.com/datawhalechina/torch-rechub). You can find the process script [here](https://github.com/datawhalechina/torch-rechub/blob/main/examples/ranking/data/ali-ccp/preprocess_ali_ccp.py). I hope this will be helpful to you.

OK. I got it. Thanks again for your patient reply!
